/**
 * Live-lane hot wallet. The secret lives ONLY in the gitignored repo-root .env
 * (TRADER_WALLET_SECRET_KEY, base58 64-byte Solana format, generated by
 * ops/live/generate-wallet.mjs). This module never logs, serializes, or
 * returns the secret — callers get the Keypair object and the address string.
 */
import { Keypair } from "@solana/web3.js";
import bs58 from "bs58";

let cached: Keypair | null | undefined;

/** The live wallet, or null when no key is configured (live lane dormant). */
export function liveWallet(): Keypair | null {
  if (cached !== undefined) return cached;
  const raw = (process.env.TRADER_WALLET_SECRET_KEY ?? "").trim();
  if (!raw) {
    cached = null;
    return cached;
  }
  try {
    const secret = bs58.decode(raw);
    if (secret.length !== 64) throw new Error(`expected 64-byte secret, got ${secret.length}`);
    cached = Keypair.fromSecretKey(secret);
  } catch (err) {
    console.error(`live wallet key unreadable — live lane stays dormant: ${err instanceof Error ? err.message : err}`);
    cached = null;
  }
  return cached;
}

export function liveWalletAddress(): string | null {
  return liveWallet()?.publicKey.toBase58() ?? null;
}
